apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-grlb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-grlb
    app.kubernetes.io/part-of: tkwch-fix-0075-0018-app
  name: devfile-sample-grlb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-grlb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-grlb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0018-tenant/tkwch-fix-0075-0018-app/devfile-sample-grlb@sha256:fbbf1173a41921e52b449cec49301b0fbe82fb57a3a0a85b9be3deb8b51001ee
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
